[package]
name = "egui_overlay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = { version = "0.44.0", git = "https://github.com/coderedart/glfw-rs.git", features = [
    "all",
] }
bytemuck = "1"
egui = { version = "0.19", features = ["bytemuck"] }
rend3 = { git = "https://github.com/BVE-Reborn/rend3.git" }
wgpu = { version = "*", features = [] }
intmap = { version = "*" }
pollster = { version = "*" }
